config-version: 2

name: tasty_bytes
version: "3.0.0"
require-dbt-version: ">=1.9.0"

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/New_York"

seeds:
  tasty_bytes:
    +schema: raw
    tasty-data:
      +enabled: "{{ var('load_source_data', false) }}"

models:
  tasty_bytes:
    staging:
      +materialized: view
    marts:
      +materialized: table
