USE ROLE sysadmin;

-- drop WAREHOUSE dbt_demo_xs_wh;
-- drop WAREHOUSE dbt_demo_s_wh;
-- drop WAREHOUSE dbt_demo_m_wh;
-- drop WAREHOUSE dbt_demo_l_wh;
-- drop WAREHOUSE dbt_demo_xl_wh;
-- drop WAREHOUSE dbt_demo_xxl_wh;

CREATE OR REPLACE WAREHOUSE dbt_demo_xs_wh
    WITH WAREHOUSE_SIZE = XSMALL
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE dbt_demo_s_wh
    WITH WAREHOUSE_SIZE = SMALL
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE dbt_demo_m_wh
    WITH WAREHOUSE_SIZE = MEDIUM
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE dbt_demo_l_wh
    WITH WAREHOUSE_SIZE = LARGE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE dbt_demo_xl_wh
    WITH WAREHOUSE_SIZE = XLARGE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE dbt_demo_xxl_wh
    WITH WAREHOUSE_SIZE = XXLARGE
    INITIALLY_SUSPENDED = TRUE;
