manifest_version: 2
type: DCM_PROJECT

targets:
  PROD:
    # The Snowflake account identifier for this target.
    account_identifier: SFSENORTHAMERICA-DGILLIS_AWS_USEAST1_V1
    #The fully qualified name of the DCM project object.
    project_name: 'util.dcm_project_archive.dbt_prod'
    # The role with OWNERSHIP on this project object.
    project_owner: ACCOUNTADMIN
    # The name of the templating configuration defined in the templating section, to use for this target.
    templating_config: 'PROD'

  DBT_PDB_DGILLIS:
    account_identifier: SFSENORTHAMERICA-DGILLIS_AWS_USEAST1_V1
    project_name: 'util.dcm_project_archive.xx_dbt_pdb_dgillis'
    project_owner: SYSADMIN
    templating_config: 'DBT_PDB'

templating:
  defaults:

    warehouses:
      - { suffix: 'xs',  size: 'XSMALL' }
      - { suffix: 's',   size: 'SMALL' }
      - { suffix: 'm',   size: 'MEDIUM' }
      - { suffix: 'l',   size: 'LARGE' }
      - { suffix: 'xl',  size: 'XLARGE' }
      - { suffix: 'xxl', size: 'XXLARGE' }

    # Schemas created in the environment database.
    schemas:
      - { name: 'raw',       comment: 'RAW data landing schema' }
      - { name: 'curated',   comment: 'Curated object schema' }
      - { name: 'modeled',   comment: 'Modeled object schema' }
      - { name: 'utilities', comment: 'global utilities and tools' }

    # Users granted the data engineer functional role.
    admin_users: []

  configurations:
    PROD:
      base: 'dbt_prod'
      env_label: 'prod'
      admin_users: [github_actions_service_user]

    DBT_PDB:
      env_label: 'pdb sandbox'
      admin_users: []
